language: java
jdk: openjdk10
install: true # Without that statement, Travis will run 'mvn install' on pom.xml before the script step.  
script: 
  - mvn install -DskipTests=true -B -V
deploy: # see https://docs.travis-ci.com/user/deployment/releases/
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  skip_cleanup: true # otherwise Travis CI will delete all the files created during the build, which will probably delete what you are trying to upload.
  overwrite: true
  file: "target/hello-jaxrs.war"
  name: "A release"
  body: "Some content"
  on:
    branch: main