language: java
jdk: openjdk10
script: 
  - mvn install -DskipTests=true -B -V
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  skip_cleanup: true
  file: "target/hello-jaxrs.war"
  name: $RELEASE_NAME
  body: $RELEASE_CONTENT
  on:
    branch: master  