version: 2.1
# see https://circleci.com/docs/language-java-maven/
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      # - run: ./mvnw -Dmaven.test.skip=true package
      - run:
          name: Testing
          command: |
            java --version
            mvn -v
            mvn test
      - run:
          name: Packaging
          command: mvn -Dmaven.test.skip=true clean package
      - run:
          name: Outdated
          command: mvn versions:display-dependency-updates
